# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('social_django', '0004_auto_20160423_0400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='association',
            unique_together=set([('server_url', 'handle')]),
        ),
        migrations.RunSQL("INSERT INTO django_migrations (app, name, applied) VALUES ('social_auth', '0001_initial', current_timestamp);", migrations.RunSQL.noop),
        migrations.RunSQL("INSERT INTO django_migrations (app, name, applied) VALUES ('social_auth', '0002_add_related_name', current_timestamp);", migrations.RunSQL.noop),
        migrations.RunSQL("INSERT INTO django_migrations (app, name, applied) VALUES ('social_auth', '0003_alter_email_max_length', current_timestamp);", migrations.RunSQL.noop),
        migrations.RunSQL("INSERT INTO django_migrations (app, name, applied) VALUES ('social_auth', '0004_auto_20160423_0400', current_timestamp);", migrations.RunSQL.noop),
        migrations.RunSQL("INSERT INTO django_migrations (app, name, applied) VALUES ('social_auth', '0005_auto_20160727_2333', current_timestamp);", migrations.RunSQL.noop),
    ]
